// System PLL - Generates 100MHz from input clock
// Altera ALTPLL megafunction

module system_pll (
    input  areset,
    input  inclk0,
    output c0,
    output locked
);

    // This is a wrapper for the Altera ALTPLL megafunction
    // Generated by MegaWizard Plug-In for Quartus II

    wire pll_areset_n = ~areset;

    altpll altpll_component (
        .areset(areset),
        .inclk({1'b0, inclk0}),
        .clk({c0}),
        .locked(locked),
        .activeclock(),
        .clkbad(),
        .clkena({1'b1}),
        .clkloss(),
        .clkswitch(1'b0),
        .configupdate(1'b0),
        .c1(),
        .c2(),
        .c3(),
        .c4(),
        .c5(),
        .extclk(),
        .extclkena({1'b1}),
        .fbin(1'b1),
        .fbmimicbidir(),
        .fbout(),
        .phasecounterselect({4{1'b0}}),
        .phasedone(),
        .phaseinc(1'b0),
        .phaseshift(1'b0),
        .scanaclr(1'b0),
        .scanclk(1'b0),
        .scanclkena(1'b1),
        .scandata(1'b0),
        .scandataout(),
        .scandone(),
        .scanread(1'b0),
        .scanwrite(1'b0),
        .sclkbusy()
    );

    defparam
        altpll_component.bandwidth_type = "AUTO",
        altpll_component.clk0_divide_by = 1,
        altpll_component.clk0_duty_cycle = 50,
        altpll_component.clk0_multiply_by = 1,
        altpll_component.clk0_phase_shift = "0",
        altpll_component.compensate_clock = "CLK0",
        altpll_component.inclk0_input_frequency = 10000,
        altpll_component.intended_device_family = "Cyclone IV E",
        altpll_component.lpm_hint = "CBX_MODULE_PREFIX=system_pll",
        altpll_component.lpm_type = "altpll",
        altpll_component.operation_mode = "NORMAL",
        altpll_component.port_activeclock = "PORT_UNUSED",
        altpll_component.port_areset = "PORT_USED",
        altpll_component.port_clkbad0 = "PORT_UNUSED",
        altpll_component.port_clkbad1 = "PORT_UNUSED",
        altpll_component.port_clkloss = "PORT_UNUSED",
        altpll_component.port_clkswitch = "PORT_UNUSED",
        altpll_component.port_configupdate = "PORT_UNUSED",
        altpll_component.port_fbin = "PORT_UNUSED",
        altpll_component.port_phasecounterselect = "PORT_UNUSED",
        altpll_component.port_phasedone = "PORT_UNUSED",
        altpll_component.port_phaseinc = "PORT_UNUSED",
        altpll_component.port_phaseshift = "PORT_UNUSED",
        altpll_component.port_scanaclr = "PORT_UNUSED",
        altpll_component.port_scanclk = "PORT_UNUSED",
        altpll_component.port_scanclkena = "PORT_UNUSED",
        altpll_component.port_scandata = "PORT_UNUSED",
        altpll_component.port_scandataout = "PORT_UNUSED",
        altpll_component.port_scandone = "PORT_UNUSED",
        altpll_component.port_scanread = "PORT_UNUSED",
        altpll_component.port_scanwrite = "PORT_UNUSED",
        altpll_component.self_reset_on_loss_of_lock = "OFF",
        altpll_component.width_clock = 5;

endmodule
